"""Add Initial Image Table

Revision ID: 2f2a42b93ab3
Revises: 
Create Date: 2020-10-16 01:59:02.496535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f2a42b93ab3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('uploadedAt', sa.DateTime(), nullable=False),
    sa.Column('isProcessed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_upload')
    # ### end Alembic commands ###
