"""Add Initial Image Table

Revision ID: 4a916694f1ba
Revises: 
Create Date: 2020-10-16 02:24:18.479608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a916694f1ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('path_uuid', sa.String(length=32), nullable=False),
    sa.Column('uploadedAt', sa.DateTime(), nullable=False),
    sa.Column('isProcessed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_upload')
    # ### end Alembic commands ###
